// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-core/rpc/ent/predicate"
	"github.com/suyuan32/simple-admin-core/rpc/ent/stockuser"
)

// StockUserQuery is the builder for querying StockUser entities.
type StockUserQuery struct {
	config
	ctx        *QueryContext
	order      []stockuser.OrderOption
	inters     []Interceptor
	predicates []predicate.StockUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StockUserQuery builder.
func (suq *StockUserQuery) Where(ps ...predicate.StockUser) *StockUserQuery {
	suq.predicates = append(suq.predicates, ps...)
	return suq
}

// Limit the number of records to be returned by this query.
func (suq *StockUserQuery) Limit(limit int) *StockUserQuery {
	suq.ctx.Limit = &limit
	return suq
}

// Offset to start from.
func (suq *StockUserQuery) Offset(offset int) *StockUserQuery {
	suq.ctx.Offset = &offset
	return suq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (suq *StockUserQuery) Unique(unique bool) *StockUserQuery {
	suq.ctx.Unique = &unique
	return suq
}

// Order specifies how the records should be ordered.
func (suq *StockUserQuery) Order(o ...stockuser.OrderOption) *StockUserQuery {
	suq.order = append(suq.order, o...)
	return suq
}

// First returns the first StockUser entity from the query.
// Returns a *NotFoundError when no StockUser was found.
func (suq *StockUserQuery) First(ctx context.Context) (*StockUser, error) {
	nodes, err := suq.Limit(1).All(setContextOp(ctx, suq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stockuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (suq *StockUserQuery) FirstX(ctx context.Context) *StockUser {
	node, err := suq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StockUser ID from the query.
// Returns a *NotFoundError when no StockUser ID was found.
func (suq *StockUserQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = suq.Limit(1).IDs(setContextOp(ctx, suq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stockuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (suq *StockUserQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := suq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StockUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StockUser entity is found.
// Returns a *NotFoundError when no StockUser entities are found.
func (suq *StockUserQuery) Only(ctx context.Context) (*StockUser, error) {
	nodes, err := suq.Limit(2).All(setContextOp(ctx, suq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stockuser.Label}
	default:
		return nil, &NotSingularError{stockuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (suq *StockUserQuery) OnlyX(ctx context.Context) *StockUser {
	node, err := suq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StockUser ID in the query.
// Returns a *NotSingularError when more than one StockUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (suq *StockUserQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = suq.Limit(2).IDs(setContextOp(ctx, suq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stockuser.Label}
	default:
		err = &NotSingularError{stockuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (suq *StockUserQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := suq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StockUsers.
func (suq *StockUserQuery) All(ctx context.Context) ([]*StockUser, error) {
	ctx = setContextOp(ctx, suq.ctx, "All")
	if err := suq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StockUser, *StockUserQuery]()
	return withInterceptors[[]*StockUser](ctx, suq, qr, suq.inters)
}

// AllX is like All, but panics if an error occurs.
func (suq *StockUserQuery) AllX(ctx context.Context) []*StockUser {
	nodes, err := suq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StockUser IDs.
func (suq *StockUserQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if suq.ctx.Unique == nil && suq.path != nil {
		suq.Unique(true)
	}
	ctx = setContextOp(ctx, suq.ctx, "IDs")
	if err = suq.Select(stockuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (suq *StockUserQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := suq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (suq *StockUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, suq.ctx, "Count")
	if err := suq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, suq, querierCount[*StockUserQuery](), suq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (suq *StockUserQuery) CountX(ctx context.Context) int {
	count, err := suq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (suq *StockUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, suq.ctx, "Exist")
	switch _, err := suq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (suq *StockUserQuery) ExistX(ctx context.Context) bool {
	exist, err := suq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StockUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (suq *StockUserQuery) Clone() *StockUserQuery {
	if suq == nil {
		return nil
	}
	return &StockUserQuery{
		config:     suq.config,
		ctx:        suq.ctx.Clone(),
		order:      append([]stockuser.OrderOption{}, suq.order...),
		inters:     append([]Interceptor{}, suq.inters...),
		predicates: append([]predicate.StockUser{}, suq.predicates...),
		// clone intermediate query.
		sql:  suq.sql.Clone(),
		path: suq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StockUser.Query().
//		GroupBy(stockuser.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (suq *StockUserQuery) GroupBy(field string, fields ...string) *StockUserGroupBy {
	suq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StockUserGroupBy{build: suq}
	grbuild.flds = &suq.ctx.Fields
	grbuild.label = stockuser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.StockUser.Query().
//		Select(stockuser.FieldCreatedAt).
//		Scan(ctx, &v)
func (suq *StockUserQuery) Select(fields ...string) *StockUserSelect {
	suq.ctx.Fields = append(suq.ctx.Fields, fields...)
	sbuild := &StockUserSelect{StockUserQuery: suq}
	sbuild.label = stockuser.Label
	sbuild.flds, sbuild.scan = &suq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StockUserSelect configured with the given aggregations.
func (suq *StockUserQuery) Aggregate(fns ...AggregateFunc) *StockUserSelect {
	return suq.Select().Aggregate(fns...)
}

func (suq *StockUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range suq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, suq); err != nil {
				return err
			}
		}
	}
	for _, f := range suq.ctx.Fields {
		if !stockuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if suq.path != nil {
		prev, err := suq.path(ctx)
		if err != nil {
			return err
		}
		suq.sql = prev
	}
	return nil
}

func (suq *StockUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StockUser, error) {
	var (
		nodes = []*StockUser{}
		_spec = suq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StockUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StockUser{config: suq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, suq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (suq *StockUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := suq.querySpec()
	_spec.Node.Columns = suq.ctx.Fields
	if len(suq.ctx.Fields) > 0 {
		_spec.Unique = suq.ctx.Unique != nil && *suq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, suq.driver, _spec)
}

func (suq *StockUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stockuser.Table, stockuser.Columns, sqlgraph.NewFieldSpec(stockuser.FieldID, field.TypeUUID))
	_spec.From = suq.sql
	if unique := suq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if suq.path != nil {
		_spec.Unique = true
	}
	if fields := suq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stockuser.FieldID)
		for i := range fields {
			if fields[i] != stockuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := suq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := suq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := suq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := suq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (suq *StockUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(suq.driver.Dialect())
	t1 := builder.Table(stockuser.Table)
	columns := suq.ctx.Fields
	if len(columns) == 0 {
		columns = stockuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if suq.sql != nil {
		selector = suq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if suq.ctx.Unique != nil && *suq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range suq.predicates {
		p(selector)
	}
	for _, p := range suq.order {
		p(selector)
	}
	if offset := suq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := suq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StockUserGroupBy is the group-by builder for StockUser entities.
type StockUserGroupBy struct {
	selector
	build *StockUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sugb *StockUserGroupBy) Aggregate(fns ...AggregateFunc) *StockUserGroupBy {
	sugb.fns = append(sugb.fns, fns...)
	return sugb
}

// Scan applies the selector query and scans the result into the given value.
func (sugb *StockUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sugb.build.ctx, "GroupBy")
	if err := sugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockUserQuery, *StockUserGroupBy](ctx, sugb.build, sugb, sugb.build.inters, v)
}

func (sugb *StockUserGroupBy) sqlScan(ctx context.Context, root *StockUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sugb.fns))
	for _, fn := range sugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sugb.flds)+len(sugb.fns))
		for _, f := range *sugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StockUserSelect is the builder for selecting fields of StockUser entities.
type StockUserSelect struct {
	*StockUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sus *StockUserSelect) Aggregate(fns ...AggregateFunc) *StockUserSelect {
	sus.fns = append(sus.fns, fns...)
	return sus
}

// Scan applies the selector query and scans the result into the given value.
func (sus *StockUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sus.ctx, "Select")
	if err := sus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockUserQuery, *StockUserSelect](ctx, sus.StockUserQuery, sus, sus.inters, v)
}

func (sus *StockUserSelect) sqlScan(ctx context.Context, root *StockUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sus.fns))
	for _, fn := range sus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
