// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-core/rpc/ent/account"
	"github.com/suyuan32/simple-admin-core/rpc/ent/post"
	"github.com/suyuan32/simple-admin-core/rpc/ent/predicate"
	"github.com/suyuan32/simple-admin-core/rpc/ent/view"
)

// ViewUpdate is the builder for updating View entities.
type ViewUpdate struct {
	config
	hooks    []Hook
	mutation *ViewMutation
}

// Where appends a list predicates to the ViewUpdate builder.
func (vu *ViewUpdate) Where(ps ...predicate.View) *ViewUpdate {
	vu.mutation.Where(ps...)
	return vu
}

// SetUpdatedAt sets the "updated_at" field.
func (vu *ViewUpdate) SetUpdatedAt(t time.Time) *ViewUpdate {
	vu.mutation.SetUpdatedAt(t)
	return vu
}

// SetStatus sets the "status" field.
func (vu *ViewUpdate) SetStatus(u uint8) *ViewUpdate {
	vu.mutation.ResetStatus()
	vu.mutation.SetStatus(u)
	return vu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (vu *ViewUpdate) SetNillableStatus(u *uint8) *ViewUpdate {
	if u != nil {
		vu.SetStatus(*u)
	}
	return vu
}

// AddStatus adds u to the "status" field.
func (vu *ViewUpdate) AddStatus(u int8) *ViewUpdate {
	vu.mutation.AddStatus(u)
	return vu
}

// ClearStatus clears the value of the "status" field.
func (vu *ViewUpdate) ClearStatus() *ViewUpdate {
	vu.mutation.ClearStatus()
	return vu
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (vu *ViewUpdate) SetAccountID(id uuid.UUID) *ViewUpdate {
	vu.mutation.SetAccountID(id)
	return vu
}

// SetNillableAccountID sets the "account" edge to the Account entity by ID if the given value is not nil.
func (vu *ViewUpdate) SetNillableAccountID(id *uuid.UUID) *ViewUpdate {
	if id != nil {
		vu = vu.SetAccountID(*id)
	}
	return vu
}

// SetAccount sets the "account" edge to the Account entity.
func (vu *ViewUpdate) SetAccount(a *Account) *ViewUpdate {
	return vu.SetAccountID(a.ID)
}

// AddPostIDs adds the "post" edge to the Post entity by IDs.
func (vu *ViewUpdate) AddPostIDs(ids ...uuid.UUID) *ViewUpdate {
	vu.mutation.AddPostIDs(ids...)
	return vu
}

// AddPost adds the "post" edges to the Post entity.
func (vu *ViewUpdate) AddPost(p ...*Post) *ViewUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return vu.AddPostIDs(ids...)
}

// Mutation returns the ViewMutation object of the builder.
func (vu *ViewUpdate) Mutation() *ViewMutation {
	return vu.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (vu *ViewUpdate) ClearAccount() *ViewUpdate {
	vu.mutation.ClearAccount()
	return vu
}

// ClearPost clears all "post" edges to the Post entity.
func (vu *ViewUpdate) ClearPost() *ViewUpdate {
	vu.mutation.ClearPost()
	return vu
}

// RemovePostIDs removes the "post" edge to Post entities by IDs.
func (vu *ViewUpdate) RemovePostIDs(ids ...uuid.UUID) *ViewUpdate {
	vu.mutation.RemovePostIDs(ids...)
	return vu
}

// RemovePost removes "post" edges to Post entities.
func (vu *ViewUpdate) RemovePost(p ...*Post) *ViewUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return vu.RemovePostIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vu *ViewUpdate) Save(ctx context.Context) (int, error) {
	vu.defaults()
	return withHooks(ctx, vu.sqlSave, vu.mutation, vu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vu *ViewUpdate) SaveX(ctx context.Context) int {
	affected, err := vu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vu *ViewUpdate) Exec(ctx context.Context) error {
	_, err := vu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vu *ViewUpdate) ExecX(ctx context.Context) {
	if err := vu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vu *ViewUpdate) defaults() {
	if _, ok := vu.mutation.UpdatedAt(); !ok {
		v := view.UpdateDefaultUpdatedAt()
		vu.mutation.SetUpdatedAt(v)
	}
}

func (vu *ViewUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(view.Table, view.Columns, sqlgraph.NewFieldSpec(view.FieldID, field.TypeUUID))
	if ps := vu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vu.mutation.UpdatedAt(); ok {
		_spec.SetField(view.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := vu.mutation.Status(); ok {
		_spec.SetField(view.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := vu.mutation.AddedStatus(); ok {
		_spec.AddField(view.FieldStatus, field.TypeUint8, value)
	}
	if vu.mutation.StatusCleared() {
		_spec.ClearField(view.FieldStatus, field.TypeUint8)
	}
	if vu.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   view.AccountTable,
			Columns: []string{view.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   view.AccountTable,
			Columns: []string{view.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vu.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   view.PostTable,
			Columns: view.PostPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.RemovedPostIDs(); len(nodes) > 0 && !vu.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   view.PostTable,
			Columns: view.PostPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   view.PostTable,
			Columns: view.PostPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{view.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	vu.mutation.done = true
	return n, nil
}

// ViewUpdateOne is the builder for updating a single View entity.
type ViewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ViewMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (vuo *ViewUpdateOne) SetUpdatedAt(t time.Time) *ViewUpdateOne {
	vuo.mutation.SetUpdatedAt(t)
	return vuo
}

// SetStatus sets the "status" field.
func (vuo *ViewUpdateOne) SetStatus(u uint8) *ViewUpdateOne {
	vuo.mutation.ResetStatus()
	vuo.mutation.SetStatus(u)
	return vuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (vuo *ViewUpdateOne) SetNillableStatus(u *uint8) *ViewUpdateOne {
	if u != nil {
		vuo.SetStatus(*u)
	}
	return vuo
}

// AddStatus adds u to the "status" field.
func (vuo *ViewUpdateOne) AddStatus(u int8) *ViewUpdateOne {
	vuo.mutation.AddStatus(u)
	return vuo
}

// ClearStatus clears the value of the "status" field.
func (vuo *ViewUpdateOne) ClearStatus() *ViewUpdateOne {
	vuo.mutation.ClearStatus()
	return vuo
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (vuo *ViewUpdateOne) SetAccountID(id uuid.UUID) *ViewUpdateOne {
	vuo.mutation.SetAccountID(id)
	return vuo
}

// SetNillableAccountID sets the "account" edge to the Account entity by ID if the given value is not nil.
func (vuo *ViewUpdateOne) SetNillableAccountID(id *uuid.UUID) *ViewUpdateOne {
	if id != nil {
		vuo = vuo.SetAccountID(*id)
	}
	return vuo
}

// SetAccount sets the "account" edge to the Account entity.
func (vuo *ViewUpdateOne) SetAccount(a *Account) *ViewUpdateOne {
	return vuo.SetAccountID(a.ID)
}

// AddPostIDs adds the "post" edge to the Post entity by IDs.
func (vuo *ViewUpdateOne) AddPostIDs(ids ...uuid.UUID) *ViewUpdateOne {
	vuo.mutation.AddPostIDs(ids...)
	return vuo
}

// AddPost adds the "post" edges to the Post entity.
func (vuo *ViewUpdateOne) AddPost(p ...*Post) *ViewUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return vuo.AddPostIDs(ids...)
}

// Mutation returns the ViewMutation object of the builder.
func (vuo *ViewUpdateOne) Mutation() *ViewMutation {
	return vuo.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (vuo *ViewUpdateOne) ClearAccount() *ViewUpdateOne {
	vuo.mutation.ClearAccount()
	return vuo
}

// ClearPost clears all "post" edges to the Post entity.
func (vuo *ViewUpdateOne) ClearPost() *ViewUpdateOne {
	vuo.mutation.ClearPost()
	return vuo
}

// RemovePostIDs removes the "post" edge to Post entities by IDs.
func (vuo *ViewUpdateOne) RemovePostIDs(ids ...uuid.UUID) *ViewUpdateOne {
	vuo.mutation.RemovePostIDs(ids...)
	return vuo
}

// RemovePost removes "post" edges to Post entities.
func (vuo *ViewUpdateOne) RemovePost(p ...*Post) *ViewUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return vuo.RemovePostIDs(ids...)
}

// Where appends a list predicates to the ViewUpdate builder.
func (vuo *ViewUpdateOne) Where(ps ...predicate.View) *ViewUpdateOne {
	vuo.mutation.Where(ps...)
	return vuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vuo *ViewUpdateOne) Select(field string, fields ...string) *ViewUpdateOne {
	vuo.fields = append([]string{field}, fields...)
	return vuo
}

// Save executes the query and returns the updated View entity.
func (vuo *ViewUpdateOne) Save(ctx context.Context) (*View, error) {
	vuo.defaults()
	return withHooks(ctx, vuo.sqlSave, vuo.mutation, vuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vuo *ViewUpdateOne) SaveX(ctx context.Context) *View {
	node, err := vuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vuo *ViewUpdateOne) Exec(ctx context.Context) error {
	_, err := vuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vuo *ViewUpdateOne) ExecX(ctx context.Context) {
	if err := vuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vuo *ViewUpdateOne) defaults() {
	if _, ok := vuo.mutation.UpdatedAt(); !ok {
		v := view.UpdateDefaultUpdatedAt()
		vuo.mutation.SetUpdatedAt(v)
	}
}

func (vuo *ViewUpdateOne) sqlSave(ctx context.Context) (_node *View, err error) {
	_spec := sqlgraph.NewUpdateSpec(view.Table, view.Columns, sqlgraph.NewFieldSpec(view.FieldID, field.TypeUUID))
	id, ok := vuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "View.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, view.FieldID)
		for _, f := range fields {
			if !view.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != view.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vuo.mutation.UpdatedAt(); ok {
		_spec.SetField(view.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := vuo.mutation.Status(); ok {
		_spec.SetField(view.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := vuo.mutation.AddedStatus(); ok {
		_spec.AddField(view.FieldStatus, field.TypeUint8, value)
	}
	if vuo.mutation.StatusCleared() {
		_spec.ClearField(view.FieldStatus, field.TypeUint8)
	}
	if vuo.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   view.AccountTable,
			Columns: []string{view.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   view.AccountTable,
			Columns: []string{view.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vuo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   view.PostTable,
			Columns: view.PostPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.RemovedPostIDs(); len(nodes) > 0 && !vuo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   view.PostTable,
			Columns: view.PostPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   view.PostTable,
			Columns: view.PostPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &View{config: vuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{view.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	vuo.mutation.done = true
	return _node, nil
}
