// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// API is the predicate function for api builders.
type API func(*sql.Selector)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Dictionary is the predicate function for dictionary builders.
type Dictionary func(*sql.Selector)

// DictionaryDetail is the predicate function for dictionarydetail builders.
type DictionaryDetail func(*sql.Selector)

// Like is the predicate function for like builders.
type Like func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// OauthProvider is the predicate function for oauthprovider builders.
type OauthProvider func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Stock is the predicate function for stock builders.
type Stock func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// View is the predicate function for view builders.
type View func(*sql.Selector)
